
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ThemeProvider from "./AppContext";

import toast, { Toaster } from "react-hot-toast";

// import { ClerkProvider } from '@clerk/nextjs'
import NavBar from "@/components/common/navbar/Navbar";

import { SideBar } from "@/constant/sidebarComponents/sideBarCompo"

import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">

      <body className={inter.className}>

        <ThemeProvider>

          {/* <NavBar /> */}

          <Toaster />

          <div className="flex flex-col bg-black">

            <NavBar />

            <div className="flex justify-between w-full ">

              <div className="relative ">

                <SideBar />

              </div>

              <div className=" overflow-x-hidden w-full">

                <NextTopLoader />
                
                {children}

              </div>

            </div>

          </div>

        </ThemeProvider>

      </body>

    </html>

  );
}


